Next.js outline
StructCE/DocStruct_old pull request #11
Opened 2023-10-10 23:49 UTC by MatheusNevs

Protótipo da documentação de Next contendo:

- Possível estruturação de pastas da documentação e personalização dos ícones;
- Breve explicação de Next;
- Como fazer instalação automática e manual;
- Documentação do tópico de roteamento de Next js, exceto API (por enquanto hehe).

2023-10-21 15:30 UTC, artistrea requested changes
- [ ] Coloque mais coisa nos metadados das suas páginas e index.yml.
    - Use como referência [esse arquivo e o próximo da PR](https://github.com/StructCE/DocStruct/pull/15/files#diff-7b2fd61a372cb243593e60d78f8bbb220ad9652df3c4cae161bd812f6d71a9ef)

**Parece** que você está tentando **traduzir a documentação** inteira deles pra cá.
Não é esse o nosso objetivo! A gente quer curar a informação, pegar só o básico e menos perigoso das pessoas fazerem errado. **Lembra que a documentação deles existe!**

**Não adianta** nada tentar **copiar** linha por linha deles **pra nossa documentação**! Busque **mudar os exemplos**, ao invés de usar ctrl+c ctrl+v, busque trocar a ordem das coisas para uma documentação mais **amigável para iniciantes**.

Como a gente falou em reunião, a **documentação** que a gente encontra **online** é um **emaranhado** de informação **pra quem sabe do que está indo atrás**. O propósito da **nossa documentação** é **guiar o pessoal iniciando**, e **quanto menos informação, e mais explicação, melhor**

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/explicacao.md
> +O diferencial deste framework está no roteamento que, para rotas estáticas, é feito de forma automática e para configurações adicionais se torna extremamente prático. Além da pré-renderização Server-
O que levou o NextJS a alta utilização no mercado é o ISR, pois possibilita a performance e SEO de página estáticas junto com o dinamismo de páginas feitas com SSR.

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/instalacao.md
> +
Acho importante frisar que não se instala nextjs de fato. Se necessita de Node instalado para poder rodar nextjs, e next é apenas formado por um conjunto de pacotes npm.

O comando para criar um app next somente copia um projeto base deles, onde já colocaram todos os pacotes e template necessários para rodar next.

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/instalacao.md
> +Como a instalação, neste caso, é manual, então algumas pastas não vem pré-configuradas no projeto. Logo, deve-se criar a pasta pages (pois estamos usando pages router) onde ficará as páginas a serem
Coloca o link de referência
https://nextjs.org/docs/getting-started/installation#the-pages-directory-optional

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/custom_pages.md
Deve-se ter apenas um H1 por página. Nesta existem 3 H1's

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/custom_pages.md
> +}
getInitialProps é legado e geralmente não deve ser usado! Além disso, a página de erro não funciona em desenvolvimento.

Acho que esse exemplo aqui é mais perigoso do que útil. No máximo deixe um link aqui tipo [veja mais sobre como customizar páginas de erro](https://nextjs.org/docs/pages/building-your-application/routing/custom-error)

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/custom_pages.md
> +Do `getInitialProps`, dentro da própria função, pegamos os parâmetros `res`e `err` que são passados pela API ao componente e verificamos se há um `statusCode` na resposta recebida, caso não haja veri
Acho melhor retirar ainda esse trecho, mas só tentando esclarecer uma parada sobre o trecho:

"os parâmetros `res`e `err` da API são passados ao componente"

1. `{res, err}` não tá sendo passado para um componente, mas para uma função normal (não retorna JSX).
2. Que api é essa que passa essas coisas? A gente não tá chamando nada, nem usando nenhuma "interface de programação de aplicação"

Pelo exemplo parece que não tem api nenhuma aí. Parece que é só o Next fazendo sua magia, pegando um erro que aconteceu em lado de servidor e jogando pro `getInitialProps` (tipo um bloco `catch(err) { Error.getInitialProps({ err, ...}) }`).

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/pages_and_layouts.md
> +
Coloca um alerta do retype aqui só pra notar que `pages/user/login.tsx` e `pages/user/login/index.tsx` produzem a mesma rota, e não pode ambos existirem

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/pages_and_layouts.md
> +Assim, pode-se importar o layout para o arquivo `_app.tsx`, onde fica a estrutura executada na aplicação:
```suggestion
Assim, pode-se importar o layout para o arquivo `_app.tsx`, onde fica a estrutura executada em todas as páginas da aplicação:
```

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/roteamento/linking_and_navigating.md
> +
Inverte a ordem dos exemplos, ou mantém somente o exemplo usando o objeto URL do Next

2023-10-21 15:30 UTC, artistrea commented on Execucao/next.js/components/index.md
Não precisa disso aqui, documentação deles é suficiente

2023-10-26 23:02 UTC, MatheusNevs commented on Execucao/next.js/roteamento/custom_pages.md
> +Do `getInitialProps`, dentro da própria função, pegamos os parâmetros `res`e `err` que são passados pela API ao componente e verificamos se há um `statusCode` na resposta recebida, caso não haja veri
Opa, tava falando dos status codes que a gente defina na api pra serem retornados em algum caso. Esses erros que a gente define são passados pra esse getInitialProps, não?

2023-10-30 12:38 UTC, artistrea commented on Execucao/next.js/roteamento/custom_pages.md
> +Do `getInitialProps`, dentro da própria função, pegamos os parâmetros `res`e `err` que são passados pela API ao componente e verificamos se há um `statusCode` na resposta recebida, caso não haja veri
@MatheusNevs essa rota só é ativada em caso de erro **do servidor**. Geralmente, erros da API a gente não levanta erro, a gente retorna resposta com status 400/500. Ou seja,

Isso leva pra essa rota daí, porque levanta erro no servidor:
```ts
export default handler() {
    throw new Error("Vai catar coquinho");
}
```

Isso é o que a gente geralmente faz, e que é a resposta da API:
```ts
export default handler() {
    res.json({ message: "Vai catar coquinho" }).status(400);
}
```

2023-11-07 01:42 UTC, MatheusNevs commented
Mandei mais commits contendo:
- Alterações que você sugeriu 
- Metadados (coloquei a fotinha do foguete como meu avatar kkkk, é pra colocar uma foto minha? )
- Tirei as páginas que estavam vazias, pq acho que nao vou fazer daquele jeito que tava fazendo de traduzir tudo msm kkk
- Um guia principal de fluxo único contendo o principal para saber Next

Senti falta talvez de falar de banco de dados na api, mas achei que talvez seria trabalho para a documentação de Prisma... Qualquer coisa eu faço se precisar, so dar um toque

2023-11-17 16:16 UTC, artistrea requested changes
Usa sintax highlight pra bash:
```bash
pnpm i next@latest
```

ao invés de
```
pnpm i next@latest
```

2023-11-17 16:16 UTC, artistrea commented on Execucao/next.js/iniciando.md
> +npx create-next-app@latest
```suggestion
pnpm create next-app
```

2023-11-17 16:16 UTC, artistrea commented on Execucao/next.js/guia.md
> +}) satisfies GetStaticProps<{data : User}>
Eu testei e isso daqui não funciona por vários motivos. Vários são consertáveis, mas um não é:
getStaticProps roda durante a build, enquanto o nosso servidor não está de pé.
Sendo assim, esse padrão sempre vai causar a **build a falhar**.

Além disso, essa sessão se chama "chamando as rotas no cliente". getStaticProps roda no servidor, não no cliente.

Acho melhor mostrar um hook custom ou react query:

```js
function useUsers() {
    const [users, setUsers] = useState<User[]>();
    const [loading, setLoading] = useState(true);
    
    useEffect(() =>{
        api.get("/api/users/")
            .then(res => {
                setUsers(res.data);
                setLoading(false);
            })
            .catch(err => alert(err.message))
    }, [])

    return users;
}
```

2023-11-23 12:21 UTC, merged