Next auth
StructCE/DocStruct_old pull request #12
Opened 2023-10-13 17:15 UTC by JoaoS4ntos

Documentação do Next Auth, aguardo feedback .

2023-10-20 02:11 UTC, artistrea requested changes
- [ ] Mude a localização da pasta `next_auth` da `Diretoria de Projetos` para uma pasta chamada `Execução` (pode criar ela na sua branch)
- [ ] Dá um merge da main com sua branch.
- [ ] Mude como configura os metadados da pasta e dos arquivos para uma [melhor maneira](https://github.com/StructCE/DocStruct/compare/main...fix/prisma#diff-7b2fd61a372cb243593e60d78f8bbb220ad9652df3c4cae161bd812f6d71a9ef)
- [ ] Adicione um trecho sobre como conseguir as credenciais para usar no Next Auth (pelo menos a de um provedor, como do Google) e como colocá-las dentro do `process.env` (usando o arquivo `.env`)

2023-10-20 02:11 UTC, artistrea commented on Diretoria Projetos/next_auth/Implementação.md
> +
Eu já encarei um troço que parecia um bug muito chato. Pra ajudar alguém quando ela encontrar o mesmo problema, sugiro **colocar um warning com um conteúdo semelhante a**:

A desestruturação dos `pageProps` em `session` e no resto das `pageProps` significa uma alteração no comportamento normal de getServerSideProps e getStaticProps.

Caso pegue a `session` no servidor e tente passar para a página como suas `pageProps`, a `session` será interceptada aqui no App e nunca chegará no seu componente da página. Ao invés disso será usada para alimentar o hook `useSession`, portanto use-o.

```tsx
export async function getServerSideProps(ctx) {
    const session = await getServerSession(ctx.req, ctx.res, authOptions);

    if (!session || !session.user) return { redirect: { permanent: false, destination: "/login" } }

    return {
        props: {
            session
        }
    }
}

// Dá erro, e a tipagem é mentirosa:
export default function HomePage({ session }: InferGetServerSidePropsType<typeof getServerSideProps>) {
    return <pre>{JSON.stringify(session.user)}</pre>
}
// Dá certo:
export default function HomePage() {
    const { data: session } = useSession();
    return <pre>{JSON.stringify(session.user)}</pre>
}
```

2023-10-20 02:11 UTC, artistrea commented on Diretoria Projetos/next_auth/Implementação.md
> +
O recomendado na documentação deles é usar as funções `signIn` e `signOut`, como no [exemplo deles](https://next-auth.js.org/getting-started/example#frontend---add-react-hook)


```suggestion

import { useSession } from "next-auth/react"

export default function Component() {
  const { data: session, status } = useSession()

  if (status === "authenticated") {
    return (
      <p>
        Signed in as {session.user.email}
        <br />
        <button onClick={() => signOut()}>Sign out</button>
      </p>
    )
  }

  return <button onClick={() => signIn()}>Sign in</button>
}

```

2023-10-20 02:11 UTC, artistrea commented on Diretoria Projetos/next_auth/explicação.md
> +Essa documentação foi desenvolvida assumindo que o leitor tem familiaridade com os conceitos básicos de Next, se n for o caso consulte o DocStruct de [Next.js]() para qualquer dúvida.
```suggestion
Essa documentação foi desenvolvida assumindo que o leitor tem familiaridade com os conceitos básicos de Next, se não for o caso consulte o DocStruct de [Next.js]() para qualquer dúvida.
```

2023-10-20 02:11 UTC, artistrea commented on Diretoria Projetos/next_auth/explicação.md
> +Essa biblioteca facilita a implementação de recursos na área de autenticação de usuário vindos de um back-end, utilizando credenciais variadas como e-mail e senha, ou utilizando autenticações externa
Next Auth na verdade é especializadao em OAuth, e dificulta implementação de cadastro e login usando email e senha. Mesmo o CredentialsProvider parece ser útil para usuários hardcoded, e a encriptação de credenciais parece que deve ser feita na mão.

Quando for necessário realizar cadastro pelo site, existem outras opções mais flexíveis, como o Lucia Auth.

2023-10-27 16:41 UTC, JoaoS4ntos commented on Diretoria Projetos/next_auth/Implementação.md
> +
adicionado

2023-10-31 13:59 UTC, artistrea requested changes

2023-10-31 13:59 UTC, artistrea commented on Execucao/next_auth/implementacao.md
> +6. Por fim, crie um arquivo `process.env` para guardar essas informações.Como no exemplo:
Isso tá muito estranho. Google Identity como API de autenticação? Tem certeza? Tenho quase certeza que tá errado. Não é pra ativar nenhuma api da google, só criar credenciais e usar.

O arquivo de guardar variáveis de ambiente não se chama `process.env`, se chama apenas `.env`.

2023-10-31 13:59 UTC, artistrea commented on Execucao/next_auth/implementacao.md
> +...
```suggestion
```bash
# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET="tefsdfadagdsdfagdf123413afadf"

NEXTAUTH_URL="http://localhost:3000"

# Next Auth GOOGLE Provider
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
```

2023-10-31 13:59 UTC, artistrea commented on Execucao/next_auth/implementacao.md
> +6. Por fim, crie um arquivo `process.env` para guardar essas informações.Como no exemplo:
Testa e me fala se tá certo

2023-11-10 15:59 UTC, JoaoS4ntos commented on Execucao/next_auth/implementacao.md
> +6. Por fim, crie um arquivo `process.env` para guardar essas informações.Como no exemplo:
Arrumei Padovas, viajei nessa API, o exemplo que eu tinha visto era uma implementação maior, acabei colocando coisa que não era essencial. Agora testei e ta dando certo

2023-11-17 12:20 UTC, artistrea approved these changes

2023-11-17 12:20 UTC, merged