Fix/prisma
StructCE/DocStruct_old pull request #15
Opened 2023-10-20 02:19 UTC by artistrea

## O que foi feito?

Alterada a documentação de Prisma feita pelo Araújo (que está na main). Foram alterados o lugar e o conteúdo dos arquivos.

Ao revisar a PR **não** precisa se **concentrar nas mudanças** em si, **mas** sim em **onde** essa documentação não está sendo clara ou **está faltando algo**, **pode ser melhor**, etc.

## Observações

Não tenha medo de colocar suas dúvidas nos comentários da PR. A dúvida pode estar mostrando um ponto onde a documentação não é clara.

Mudei o CNAME sem querer, mas pode deixar aí que é bom alterar mesmo.

2023-11-10 18:40 UTC, pafev requested changes
Ficou muito boa a documentação. No que se refere a código, não achei nada para apontar ou sugerir. No que se refere a textos, pedi algo mais explicado e completo.

Ia pedir para falar mais sobre os métodos e os filtros nas queries, mas como vc colocou a documentação do Prisma como referência, já tá bom

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/explicacao.md
> +O [prisma](https://www.prisma.io) é uma biblioteca desenvolvida em typescript que pode ser usada com JS/TS. Ela possui diferentes módulos, entre eles estão:
```suggestion
O [prisma](https://www.prisma.io) é uma biblioteca desenvolvida em TypeScript, que tem suporte para ser usada nas linguagens .js/.ts. Ela possui diferentes módulos, entre eles estão:
```

esse JS/TS pode ficar confuso. Parece sigla de algum daqueles termos conceituais de programação, como CI/CD. Aí a pessoa lê e pensa "JS/TS é sigla de que? aaah é JavaScript ou TypeScript, tendeu"

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/explicacao.md
> +- Prisma Client;
Acho que faz mais sentido, nessa divisão de módulos, o Prisma Studio estar tão separado do Prisma db/migrate quanto do Prisma Client, já que ele é uma GUI e por sinal é a única parte do Prisma que não é open-source. É tratado como uma coisa a parte msm, estando na sessão de Prisma Data Platform

Aí a divisão seria:
- Prisma db/migrate
- Prisma Studio
- Prisma Client

Tal qual é na documentação oficial do Prisma

```suggestion
- Prisma db/migrate;
- Prisma Studio;
- Prisma Client;
```

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/explicacao.md
> +A ideia do Prisma é ser uma ORM. Ela pode ser utilizada no desenvolvimento de aplicativos de banco de dados em JavaScript ou TypeScript. Ela é bem amigável com iniciantes e permite segurança de tipos
```suggestion
A ideia do Prisma é ser uma ORM. Ela pode ser utilizada no desenvolvimento de aplicações em JavaScript ou TypeScript, que necessitem de alguma estrutura de banco de dados. Ela é bem amigável com iniciantes - devido à sintaxe de fácil entendimento e à facilidade de construção das models - e permite segurança de tipos. Não é a melhor em questão de performance, mas a gente nunca precisou de performance (pelo menos por enquanto).
```

Sugeri essa alteração, mas não sei se entendi o que você quis dizer com "aplicações de banco de dados"

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/explicacao.md
> +A ideia do Prisma é ser uma ORM. Ela pode ser utilizada no desenvolvimento de aplicativos de banco de dados em JavaScript ou TypeScript. Ela é bem amigável com iniciantes e permite segurança de tipos
Para enriquecer a introdução e do por que utilizamos Prisma, seria válido adicionar ou explicar melhor os seguintes tópicos:

Explicar melhor:
- Por que ela é bem amigável com inciantes? Por causa da sintaxe intuitiva e da facilidade de construção das models?
- Por que a construção de uma API com segurança de tipos é tão boa? Pode falar do auto-complete e do apontamento de erros no vscode, te permitindo acessar métodos e propriedades, sem precisar ficar revisitando o esquema do banco de dados o tempo todo, e te impedindo de acessar acidentalmente uma propriedade que não existe.

Adicionar:
- Construção de métodos versáteis e diversos que te permitem melhor acessar e interagir com seu banco de dados (há lógicas de filtros pré-implementadas, ordenação, etc.). Aqui neste tópico, não precisa explicitamente falar do nome "Prisma Client API", já que este parece ser um texto de introdução de ideias e motivações né

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/explicacao.md
> +O _core_ dessa biblioteca é o pacote `prisma`, que **permite que você altere o schema**, se conectando a um banco de dados. Por padrão ele usa o arquivo em `prisma/schema.prisma` como base para atual
```suggestion
O _core_ dessa biblioteca é o pacote `prisma`, que **permite que** você **se conecte a um banco de dados e construa ou altere o seu schema**, ou seja, construa ou altere a modelagem das entidades que seu banco de dados implementa. Por padrão ele usa o arquivo em `prisma/schema.prisma` como base para atualizar o schema do banco de dados, e necessita de uma variável de ambiente para localizar o banco de dados a ser alterado pelos comandos.
```

Alterei a ordem, mas é pq seria bom falar o que é schema no final, já que vc utilizou este termo por toda a documentação.

Não sei se vale a pena falar, mas schema do banco de dados e [Prisma schema](https://www.prisma.io/docs/concepts/components/prisma-schema) parecem ser coisas diferentes, o Prisma schema é composto pela Datasource (conexão com banco de dados), Data Model (criação das models) e Generators (onde vc estabelece a criação de um Prisma Client). Tudo isso está no Prisma schema, ou seja, ele é o schema e mais um pouco

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +`prisma/schema.prisma`: o arquivo de configuração principal para o seu projeto Prisma (incluirá o seu modelo de dados).
```suggestion
`.env`: o arquivo para definir a URL de conexão do seu banco de dados.

`prisma/schema.prisma`: o arquivo de configuração principal para o seu projeto Prisma (incluirá o seu modelo de dados).
```

Parece que o retype não entende direito a quebra de linha

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +```bash
sugestão: para estes comandos de bash, colocar as opções para outros gerenciadores de pacotes. Acho que fica mais completinho

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +Muitas vezes **não é bom** usar **SQLite em produção**. Por esse motivo, atualmente (em 2023) **trocamos de SQLite para MySQL** ao entrar em produção. Isso **torna necessário** realizar **mudanças**,
muito bom tu ter comentado isso, parabéns

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +A **maneira anterior pode causar vazamento de memória em ambiente de desenvolvimento**. Às vezes ao recarregar a aplicação, que acontece quando salvas um arquivo, o código que gera o cliente é rodado
```suggestion
A **maneira anterior pode causar vazamento de memória em ambiente de desenvolvimento**. Às vezes, ao recarregar a aplicação, que acontece quando salvamos um arquivo, o código que gera o cliente é rodado outra vez. Isso pode acabar gerando várias instâncias.
```

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +**É importante ressaltar que nesse passo o Docker esta sendo utilizado como um 'simulador'
```suggestion
**É importante ressaltar que nesse passo o Docker está sendo utilizado como um 'simulador'
```

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +## Configurar banco de dados PostgreSQL usando o Docker
Sinto que faltou explicar o por quê deste tópico existir, elaborando, para isso, um parágrafo de introdução

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +
Antes de partir para o passo a passo da configuração do docker compose e do seu container para o postgresql, recomende alguma documentação ou referẽncia de docker, para a pessoa ver e se contextualizar, já que docker não é um conhecimento básico da Struct

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/instalacao.md
> +Declare a URL do banco de dados substituindo as `{var}` por seus valores:
```suggestion
Na variável de ambiente abaixo, declare a URL do banco de dados, substituindo os termos entre chaves, `{var}`, por seus respectivos valores:
```

Só para ficar um pouco mais claro

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/utilizacao.md
> +
Seria bom falar da geração de uma Prisma Client, pelo generator, e da conexão com um banco de dados, pelo datasource. Pelo menos só falar, não precisa aprofundar. É para quem está lendo não achar que ficou incompleto seu entendimento sobre Prisma Schema

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/utilizacao.md
> +É possível gerar migrações em `.sql` ou simplesmente forçar o schema do banco de dados a atualizar. **Em desenvolvimento, o recomendado é** forçar a atualização, e simplesmente **rodar**:
```suggestion
É possível gerar migrações em `.sql` - ou seja, arquivos escritos em código _sql_, que contém as alterações realizadas no schema.prisma e que devem ser migradas para o schema do seu banco de dados -, ou simplesmente forçar o schema do banco de dados a atualizar. **Em desenvolvimento, o recomendado é** forçar a atualização, e simplesmente **rodar o seguinte comando**:
```

Lembrar que a documentação será lida até por trainees que estão vendo uma ORM pela primeira vez

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/utilizacao.md
> +Neste exemplo, estamos rodando os arquivos com ts-node, que transpila o TS e roda o JS resultante com Node. A ideia é a mesma usando api em Express, NextJS, etc.
```suggestion
Neste exemplo, estamos rodando os arquivos com ts-node, que transpila o TypeScript e roda o JavaScript resultante com Node. A ideia é a mesma usando api em Express, NextJS, etc.
```

2023-11-10 18:40 UTC, pafev commented on Execucao/prisma/utilizacao.md
> +
```suggestion

CRUD é uma acrônimo para as quatro maneiras básicas de se operar com informações armazenadas em uma aplicação. Estas operações são: **Create**, **Read**, **Update** e **Delete**.

Então, a seguir seguem formas de construirmos um CRUD utiilizando o Prisma, para interação com as instâncias do nosso banco de dados.

```

Pode parecer descrição e explicação demais, mas estou pensando em como essas documentações de ferramentas irão servir não só para os membros efetivos da Struct, como também para os trainees

2023-11-21 02:26 UTC, artistrea commented on Execucao/prisma/utilizacao.md
> +Neste exemplo, estamos rodando os arquivos com ts-node, que transpila o TS e roda o JS resultante com Node. A ideia é a mesma usando api em Express, NextJS, etc.
Depois fala que não faz nitpick.

ME RECUSO

2023-11-24 18:48 UTC, merged