Documentação NextAuth com T3 [DRAFT]
StructCE/DocStruct_old pull request #26
Opened 2024-02-26 14:01 UTC by marqueswill

#### O que falta?

- [x]  Reorganizar documentação antiga
- [x] Fetch e PreFetch (session no client e server side)
- [x] Personalização dos dados de session
- [ ]  Métodos SignIn e SignOut
- [x] Proteção de rotas com App Router
- [ ]  Criptografia de senhas pro credentials provider

2024-02-28 00:59 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
É bom toda página ter um h1(#), algo que represente o assunto geral

2024-02-28 00:59 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +
O Auth é o principal processo de autenticação usado atualmente, inclusive pelas empresas citadas, e o NextAuth "terceiriza" sua autenticação usando a de empresas externas

2024-02-28 01:00 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +  profile(profile) {
Não consegui achar documentação desse profile hehe, acho que você pode tirar se não acaba confundindo e o importante mesmo são as credenciais

2024-02-28 01:01 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +OAuth é o processo de autenticação do NextAuth que utiliza de provedores de login externos preexistentes que dão ao usúario a opção de realizar a autenticação por meio de outra plataforma como Google
O Auth é o principal processo de autenticação usado atualmente, inclusive pelas empresas citadas, e o NextAuth "terceiriza" sua autenticação usando a de empresas externas

2024-02-28 01:02 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +A autenticação por Credenciais permite lidar com o login usando credenciais arbitrárias, como nome de usuário e senha, ele vem com a restrição de que os usuários autenticados dessa maneira não se man
Essa ideia de token para validar uma sessão de usuário é a ideia do OAuth, usada na autenticação externa. Eu tentei dar uma pesquisada, mas a documentação do nextAuth sobre credentials é tão pouca, assisti um vídeo de um indiano kaka e, pelo que entendi mais ou menos de tudo, é que a validação não é feita igual OAuth (por token) e sim manualmente pela definição da função authorize() na configuração do [provider](https://next-auth.js.org/providers/credentials#options)

2024-02-28 01:02 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +O Next pode tentar carregar o `bcrypt` no client-side! Para que isso não aconteça, é importante especificar no `next.config.js` que essa biblioteca deve permanecer apenas no escopo do server-side:
Fale do motivo (estamos usando App Router, que, por padrão, renderiza suas páginas no server side)

2024-02-28 01:04 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Por isso, quando você for realizar registro de usuários na sua database, é recomendado que você utilize alguma forma de criptografia para as senhas armazenadas. Uma solução para isso é utilizar bibli
A parte do bcrypt você pode deixar só um link para a documentação deles. Explicar a parte do authorize já é a ideia, se não acaba ficando muito extenso

2024-02-28 01:04 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Nesse caso, crie um arquivo chamado `route.js` na pasta `app/api/auth/[...nextauth]/route.ts` e preencha-o com o código a baixo.
Dê uma explicada aqui que deve-se usar handler porque é a função executada quando a API é chamada

2024-02-28 01:05 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +O NextAuth provê medidas de controle de sessão para que você consiga iniciar e encerrar sessões facilmente. Embora você tenha um conector entre o Prisma e o NextAuth, você precisa implementar a lógic
Não entendi essa parte, não precisa implementar lógico de registro de usuário (a menos que seja credentials)

2024-02-28 01:05 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Acesso:
Pode ficar um pouco confuso acesso com signIn, o que o signIn vai fazer é criar uma sessão de usuário no banco de dados a partir de uma interação do usuário com o client, login, (sendo um client component), o acesso/session em si é feito pelo getServerAuthSession() (server component). É bom só colocar que signIn é um client component e então deve-se usar "use client".

2024-02-28 01:06 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +No caso do `crendentials` ou `email` provider, além das opções acima, você tem a possibilidade lidar com a resposta do `SignIn()` na página em que a função é chamada ao **desabilitar seu redirecionam
Você deixou um exemplo bom, mas deixa um pouco mais claro aqui que a página em que a função seria chamada teria que ser uma página de cadastro/login com forms e tudo, porque estaria deixando de usar a que o nextAuth provê

2024-02-28 01:06 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +### Fetching
Os outros títulos são autoexplicativos, mas esse pode não ser tanto assim. É bom ter uma descriçãozinha aqui falando que aqui vemos como pegar dados da sessão

2024-02-28 01:07 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +export default function RootLayout({
O App Router é renderizado por padrão no server side então não da pra envolver o layout raiz do projeto com um Session Provider (client component), pois você precisaria usar "use client" no layout root do projeto e deixaria todo o projeto client-side-rendering o que não é do App Router

2024-02-28 01:07 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +export default function RootLayout({
useSession e SessionProvider são client components usados principalmente no Pages Router, até dá pra colocar em algum lugar de um projeto em App Router, mas é melhor usar getServerSession ou getAuthServerSession do NextAuth, dá uma esclarecida nessas diferenças

2024-02-28 01:08 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +### Fetching
Falando de toda a parte de Fetching -> Aqui na parte de fetching você exemplificou bastante e falou de muitas maneiras de fazer a busca da sessão, isso pode ser bom, mas a ideia da nossa documentação é ter o essencial e prático, caso a pessoa queria aprender mais você aponta um link do assunto. Também falou das duas tecnologias do Next, o App e Pages router, e acabou misturando algumas vezes, pra ficar bem prática e, como é a nossa tecnologia atual, acho que seria melhor falar somente sobre App Router (ignore caso o Paulete tenha pedido as duas haha, mas ainda dê uma resumida) e os seus componentes para busca de sessão que são ou o getServerSession ou o getAuthServerSession (dar prioridade pro último e uma explicaçãozinha já que a nossa stack é a T3)

2024-02-28 01:11 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Dessa forma podemos criar, por exemplo, um parâmetro para o `User` no schema que indique se o usuário é um administrador e passar essa informação nos dados de sessão para as páginas, o que possibilit
É possível fazer isso só que não daria pra enfiar um parametro novo no signIn, a não ser que você use um adaptador customizado o que é meio complicado. Fale que, caso haja um parâmetro novo, ele deve ser opcional pois o prisma irá dar erro caso não encontre-o, o que vai acontecer. E, para criar usuários admins, você pode usar a seed.

2024-02-28 01:13 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +      <AuthProvider>{children}</AuthProvider>;
AuthProvider é client component, não faz muito sentido usar ele aqui, você pode passar o session como props do children, isso se for preciso

2024-02-28 11:00 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +  profile(profile) {
Eita nem tinha visto, isso aí é da documentação antiga

2024-02-28 11:08 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +A autenticação por Credenciais permite lidar com o login usando credenciais arbitrárias, como nome de usuário e senha, ele vem com a restrição de que os usuários autenticados dessa maneira não se man
Documentação antiga também

2024-02-28 11:44 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +O NextAuth provê medidas de controle de sessão para que você consiga iniciar e encerrar sessões facilmente. Embora você tenha um conector entre o Prisma e o NextAuth, você precisa implementar a lógic
é porque tem signin e signout mas não tem um "signUp", então achei uma boa ideia falar que pra registrar usuário na database você tem que se virar
Talvez assim fique menos confuso:

"O NextAuth provê medidas de controle de sessão para que você consiga iniciar (SignIn) e encerrar (SignOut) sessões facilmente. Em relação à lógica de registro (SignUp) para o credentials provider, é necessário implementá-la manualmente criando o `User` por conta própria na database!"

2024-02-28 11:45 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +O NextAuth provê medidas de controle de sessão para que você consiga iniciar e encerrar sessões facilmente. Embora você tenha um conector entre o Prisma e o NextAuth, você precisa implementar a lógic
Mas se pá como eu to falando de controle da sessão não faz sentido falar disso ai

2024-02-28 11:52 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Acesso:
esse acesso ficou confuso mesmo, ele se refere se a função é acessada pelo client ou server side
Talvez se eu colocar "localização" ou "execução" fique menos ambiguo

2024-02-28 12:32 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +### Fetching
Retirei a parte do pages router que era da documentação antiga
Retirei o getSession e coloquei link pra documentaçao
Retirei tudo relacionado ao getServerSideProps da documentação antiga

2024-02-28 12:53 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +OAuth é o processo de autenticação do NextAuth que utiliza de provedores de login externos preexistentes que dão ao usúario a opção de realizar a autenticação por meio de outra plataforma como Google
Reformulei o texto

2024-02-28 12:55 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +A autenticação por Credenciais permite lidar com o login usando credenciais arbitrárias, como nome de usuário e senha, ele vem com a restrição de que os usuários autenticados dessa maneira não se man
Retirei essa parte  para falar que a verificação é no authorize e coloquei o exemplo mais perto

2024-02-28 12:56 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Por isso, quando você for realizar registro de usuários na sua database, é recomendado que você utilize alguma forma de criptografia para as senhas armazenadas. Uma solução para isso é utilizar bibli
Decidi manter o warning em relação à segurança do credentials provider
Tirei toda parte relacionada ao bcrypt e coloquei um link pra documentação deles

2024-02-28 12:57 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
Coloquei o título como sendo
"Guia de uso NextAuth com T3"

2024-02-28 12:58 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +  profile(profile) {
Apaguei esse exemplo pq na seção de providers já tem outros exemplos melhores

2024-02-28 12:59 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +No caso do `crendentials` ou `email` provider, além das opções acima, você tem a possibilidade lidar com a resposta do `SignIn()` na página em que a função é chamada ao **desabilitar seu redirecionam
Ressaltei que essa parte é para uma página de login própria

2024-02-28 13:00 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +      <AuthProvider>{children}</AuthProvider>;
Tinha feito seguindo um exemplo do paulo e já removi a parte do AuthProvider

2024-02-28 13:48 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +O Next pode tentar carregar o `bcrypt` no client-side! Para que isso não aconteça, é importante especificar no `next.config.js` que essa biblioteca deve permanecer apenas no escopo do server-side:
retirei essa parte junto com o bcrypt

2024-02-28 13:48 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +export default function RootLayout({
ops

2024-02-28 13:49 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +export default function RootLayout({
retirei isso e trouxe a parte de proteção de rotas pro início já que ela aborda essa parte de session provider

2024-02-28 14:45 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Nesse caso, crie um arquivo chamado `route.js` na pasta `app/api/auth/[...nextauth]/route.ts` e preencha-o com o código a baixo.
Coloquei uma mini explicação, decidi não aprofundar na parte de route handler pq ai é documentacao do next

2024-02-28 16:06 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Acesso:
Tirei o isAdmin e retornei para o parâmetro "id" que é o que o T3 dá de exemplo

2024-02-28 16:06 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Dessa forma podemos criar, por exemplo, um parâmetro para o `User` no schema que indique se o usuário é um administrador e passar essa informação nos dados de sessão para as páginas, o que possibilit
Tirei o isAdmin e retornei para o parâmetro "id" que é o que o T3 dá de exemplo

2024-02-28 22:21 UTC, pafev requested changes

2024-02-28 22:21 UTC, pafev commented on Execucao/next_auth/implementacao.md
> +}
tem duas coisas aqui:
- tá ocorrendo a importação do AuthProvider e utilização do SessionProvider
- não rola utilizar o SessionProvider diretamente, pq vc precisa da diretiva "use client" e ela não funciona bem em arquivos layout.tsx

2024-02-28 22:21 UTC, pafev commented on Execucao/next_auth/implementacao.md
> +}
em contrapartida, vc precisa do SessionProvider, para chamar useSession nas páginas com autenticação (isso pq esse mecanismo funciona por useContext por baixo dos panos)

2024-02-28 22:21 UTC, pafev commented on Execucao/next_auth/implementacao.md
> +}
Tem uma solução para isso

2024-02-28 22:21 UTC, pafev commented on Execucao/next_auth/implementacao.md
> +Nesse exemplo, temos um grupo de rotas chamado `(user)` que agrupa todas páginas relacionadas ao perfil de um usuário qualquer. O `SessionProvider` engloba o `children`, definindo que para acessar qu
Vc consegue acessar uma página que está sendo englobada pelo SessionProvider, sem estar com a sessão, ou seja, sem o usuário estar logado. É só não chamar a sessão na página
O papel do SessionProvider é mais prover acesso ao hook useSession

2024-02-29 11:52 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Nesse exemplo, temos um grupo de rotas chamado `(user)` que agrupa todas páginas relacionadas ao perfil de um usuário qualquer. O `SessionProvider` engloba o `children`, definindo que para acessar qu
ficou meio confuso mesmo, o que eu quis dizer é que o layout usa a existencia do session pra definir que as página precisa de login pra ser acessada, não o session provider
refiz o texto pra tirar a ambiguidade

2024-02-29 11:56 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +}
o matheus tinha mandado tirar o AuthProvider vou por ele de volta então

2024-02-29 12:07 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +}
coloquei de volta e fiz um mini disclaimer melhor sobre o porquê o <AuthProvider> é utilizado

2024-02-29 12:28 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Dessa forma podemos criar, por exemplo, um parâmetro para o `User` no schema que indique se o usuário é um administrador e passar essa informação nos dados de sessão para as páginas, o que possibilit
tinha entendido errado mb
refiz o exemplo do session callback para o credentials provider

2024-02-29 17:34 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +O `credentials provider` permite lidar com o login usando credenciais arbitrárias, como nome de usuário e senha. A validação de sessão com base no banco de dados deve ser realizada de forma por meio
```suggestion
O `credentials provider` permite lidar com o login usando credenciais arbitrárias, como nome de usuário e senha. A validação de sessão com base no banco de dados deve ser realizada de forma manual por meio da função `authorize()` na configuração dos providers no NextAuth.
```

2024-02-29 17:36 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +import { compare } from "bcrypt"
```suggestion

```

2024-02-29 20:26 UTC, MatheusNevs commented
Você acabou tirando a parte que explicava como definir o provider de terceiros como o do google, precisa deixar aquela parte lá, só pode tirar a parte do profile que ficou confusa.

2024-02-29 20:27 UTC, MatheusNevs commented
A parte de proteção de rotas coloca só depois de fetching de sessão, pq precisa dessa parte pra fazer um layout pra proteger as rotas. Pode colocar logo depois de fetching.

2024-02-29 20:29 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Dentro do grupo `(user)` podemos ter uma página com rota dinâmica para o perfil do usuário e uma página de login genérica. Nessa página de login, de maneira análoga ao layout, direcionamos o usuário
Rota dinamica é entre [], () faz só não aparecer a parte que está dentro na rota do navegador

2024-02-29 20:29 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +export default async function LoginPage() {
Quando você está em um sessionProvider, a ideia é você pegar a sessão pelo useSession. Se você não estiver usando um provider daí usa getServerAuthSession()

2024-02-29 20:30 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +export default async function LoginPage() {
A ideia de usar o layout que você fez no exemplo anterior é para ter as páginas que precisam necessariamente estar logado, então não seria uma boa a pagina de log in ficar dentro dela

2024-02-29 20:30 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +export default async function ProfilePage() {
Acho q não precisa desse exemplo

2024-02-29 20:31 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +No caso do NextAuth, temos um handler padrão definido que é executado sempre que a API de autenticação é chamada na rota `api/auth`. Ele é necessário para que o funcionamento das funções `SignIn()`,
```suggestion
No caso do NextAuth, temos um handler padrão definido que é executado sempre que a API de autenticação é chamada na rota `api/auth`. Ele é necessário para o funcionamento das funções `SignIn()`, `SignOut()` entre outras coisas.
```

2024-02-29 20:32 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +Não existe função SignUp para registro de usuários! Caso você esteja utilizando o `credentials provider` e queira registrar um usuário, você deve fazer isso manualmente
Também não existe uma função signUp pra externos, o registro do usuário é feito no signIn caso já não esteja no banco de dados. A diferença é que agora essa parte, usando credentials, deve ser feita manualmente

2024-02-29 20:33 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
>  const SigninButton = () => {
Da uma trocada no nome desse componente, como signButton, pq ele pode ser tanto de signIn como de signOut, daí pode acabar confundindo.

2024-02-29 20:34 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +A stack do T3 oferece a função auxiliar `getServerAuthSession` para fazer o pre-fetch da sessão no server-side. Essa função é parecida com a `getServerSession`, mas com a vantagem de que você não pre
Paulete me mostrou que apesar de authprovider ser um client component, tudo que estiver dentro dele não necessariamente será um client component. getServerSideProps é usado em Pages Router (renderiza por padrão no client side) quando você quer renderizar as pages no server side. Não é usado em App Router. Nossa documentação de next foi feita para Pages Router, se quiser dá uma olhada la

2024-02-29 20:34 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +A stack do T3 oferece a função auxiliar `getServerAuthSession` para fazer o pre-fetch da sessão no server-side. Essa função é parecida com a `getServerSession`, mas com a vantagem de que você não pre
Aqui você pode só falar do exemplo anterior, com a opção de substituir o getServerSession(authOptions) por somente getAuthServerSession()

2024-02-29 20:46 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
>  ```
getServerSideProps é de pages router, coloca um exemplo facil como:
```
import { getAuthServerSession } from "~/server/auth";

export default function HomePage() {
  const session = getAuthServerSession()
  // Use se não estiver usando um provider, caso contrário use useSession()
  return <pre>{JSON.stringify(session.user)}</pre>;
}
```
Fale que se tiver provider, pode-se usar o useSession invés de getAuthServerSession

2024-02-29 20:47 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +        isAuthorized: user.isAuthorized      // novo parâmetro para o objeto user da session
Aqui fala que deve-se fazer uma validação para algum caso em que seja true, porque pelo banco de dados sempre será false

2024-02-29 20:48 UTC, MatheusNevs commented on Execucao/next_auth/implementacao.md
> +      // return false
Ficou meio confuso, simplifique mais, como:
```ts
async signIn({ user, account, profile, email, credentials }) {
    // você precisa fazer a lógica aqui ou pegar da db. Ex:
    if (email.endsWith("@struct.unb.br"))
      return true
      // Você pode retornar uma URL de redirecionamento
    return "/unauthorized"
      // Ou pode retornar `false` para mostrar uma mensagem de erro padrão
      // return false
    }
```

2024-03-04 15:48 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +Dentro do grupo `(user)` podemos ter uma página com rota dinâmica para o perfil do usuário e uma página de login genérica. Nessa página de login, de maneira análoga ao layout, direcionamos o usuário
Especifiquei as rotas no texto e coloquei um link para documentação de rota dinâmica do nextjs

2024-03-04 15:48 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +export default async function LoginPage() {
bem notado

2024-03-04 15:55 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +export default async function ProfilePage() {
acho que precisa, porque é uma demonstração de uma das muitas maneiras de como utilizar o grupo de rotas

2024-03-04 16:07 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
>  const SigninButton = () => {
troquei pra SessionControlButton

2024-03-04 16:11 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
>  ```
eita nao era pra isso ter ido no commit, acabei esquecendo de tirar essas funções

2024-03-04 16:14 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +A stack do T3 oferece a função auxiliar `getServerAuthSession` para fazer o pre-fetch da sessão no server-side. Essa função é parecida com a `getServerSession`, mas com a vantagem de que você não pre
esqueci de retirar no ultimo commit

2024-03-04 16:18 UTC, marqueswill commented on Execucao/next_auth/implementacao.md
> +        isAuthorized: user.isAuthorized      // novo parâmetro para o objeto user da session
coloquei um parametro generico de exemplo

2024-03-06 14:03 UTC, MatheusNevs commented
Ficou bom @marqueswill, só vou ver se o Paulo quer dar uma olhada antes de eu dar o merge

2024-03-07 20:38 UTC, pafev approved these changes

2024-03-07 20:39 UTC, merged