[DRAFT] DOCS: Next App Router
StructCE/DocStruct_old pull request #27
Opened 2024-02-27 11:58 UTC by PedroAmorimG

Parte de roteamento possivelmente pronta.

2024-03-03 11:51 UTC, PedroAmorimG commented
Parte de roteamento e APIs feita, necessitam de revisão.

2024-03-06 13:14 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +O `App Router` foi introduzido na versão 13 do next.js e foi construído utilizando o `React Server Components`.
Acho uma boa colocar aqui a sigla que você usou pra se referir aos RSCs depois.
```suggestion
O `App Router` foi introduzido na versão 13 do next.js e foi construído utilizando o `React Server Components (RSC)`.
```

2024-03-06 13:16 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +O `App Router` trabalha com o diretório app para a criação de rotas que podem ou não serem de acesso público, por padrão componentes deste diretório são `RSCs`. As páginas são criadas nas rotas e irã
Só umas correções de português e de estrutura da frase
```suggestion
O `App Router` trabalha com o diretório app para a criação de rotas que podem ou não ser de acesso público. Por padrão, componentes deste diretório são `RSCs`. As páginas são criadas nas rotas e irão herdar certas características definidas por arquivos especiais, como `navbar` e `footer`, definidos no arquivo `layout.tsx` da rota.
```

2024-03-06 13:18 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Para mais informações sobre [React Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components).
Sugestão de estrutura, de novo
```suggestion
Para mais informações, acesse [React Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components).
```

2024-03-06 13:19 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +O App Router não trabalha exclusivamente com `server components`, se for necessário o uso de `client components` adicione a linha `"use client"` no topo do arquivo da página.
```suggestion
O App Router não trabalha exclusivamente com `server components`. Se for necessário o uso de `client components`, adicione a linha `"use client"` no topo do arquivo da página.
```

2024-03-06 13:47 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Esses arquivos deverão ser da extensão `.js`, `.jsx` ou .tsx. Dê preferência ao uso da extensão `.tsx `(TypeScript).
```suggestion
Esses arquivos deverão ser da extensão `.js`, `.jsx` ou `.tsx`. Dê preferência ao uso da extensão `.tsx` (TypeScript).
```

2024-03-06 13:48 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +As páginas são arquivos com o nome `page.tsx` que apresentam a estrutura do React e vão desempenhar o papel de criar UIs especificas a determinada rota. Elas tornam a rota acessível para visitantes e
```suggestion
As páginas são arquivos com o nome `page.tsx` que apresentam a estrutura do React e vão desempenhar o papel de criar UIs especificas a determinada rota. Elas tornam a rota acessível para visitantes e por padrão são Server Components.
```

2024-03-06 13:54 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Uma rota é publicamente acessível, somente se existir um arquivo do tipo `page.tsx` ou `route.ts`.
```suggestion
Uma rota é publicamente acessível somente se existir um arquivo do tipo `page.tsx` ou `route.ts`.
```

2024-03-06 13:56 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Para padrões avançados de roteamento, como Rotas em paralelo ou interceptação de rotas, [veja](https://nextjs.org/docs/app/building-your-application/routing#advanced-routing-patterns)
Outra sugestão de estrutura da frase. Pode mudar o que adicionei pro que achar melhor
```suggestion
Para padrões avançados de roteamento, como Rotas em paralelo ou interceptação de rotas, veja *[Advanced Routing Patterns](https://nextjs.org/docs/app/building-your-application/routing#advanced-routing-patterns)*
```

2024-03-06 13:58 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Para mais informações sobre [redirecionamento](https://nextjs.org/docs/app/building-your-application/routing/redirecting).
```suggestion
Para mais informações, acesse [redirecionamento](https://nextjs.org/docs/app/building-your-application/routing/redirecting).
```

2024-03-06 14:00 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Para criar uma rota API é necessário escrever um arquivo com o nome `route.ts`, nele será construída a API da rota.
```suggestion
Para criar uma rota API é necessário escrever um arquivo com o nome `route.ts`, onde será construída a API da rota.
```

2024-03-06 14:01 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Por fim, as APIs `route handler` do next precisam do `return` de uma `Response`, nessa `Response` utilize o método `json` para a transmissão dos dados coletados ou código de status.
```suggestion
Por fim, as APIs `route handler` do next precisam do `return` de uma `Response`. Nessa `Response` utilize o método `json` para a transmissão dos dados coletados ou código de status.
```

2024-03-06 14:02 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Em uma rota não pode conter uma `page` e um `route handler` ao mesmo tempo, pois haverá conflito e o `route handler` prevalecerá. Por isso, recomendo criar um diretório `api` na rota para colocar o `
```suggestion
Em uma rota não pode conter uma `page` e um `route handler` ao mesmo tempo, pois haverá conflito e o `route handler` prevalecerá. Por isso, é recomendado criar um diretório `api` na rota para colocar o `route handler`.
```

2024-03-06 14:04 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Podemos utilizar diferentes métodos para a busca de dados para formar a página do site, sendo eles `server-side` ou `client-side`, normalmente esses dados serão recebidos em formato `JSON`. Os dados
```suggestion
Podemos utilizar diferentes métodos para a busca de dados para formar a página do site, sendo eles `server-side` ou `client-side`. Normalmente, esses dados serão recebidos em formato `JSON`. Os dados podem vir de APIs existentes na internet ou de APIs internas alimentadas com o próprio banco de dados para `client components`, ou então podem vir de APIs externas ou diretamente do banco de dados para os `server components`.
```

2024-03-06 14:05 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Quando precisamos buscar dados para criar a página no lado do servidor pode-se utilizar `fetch` ou `axios` para buscar por dados externos e uma função com busca direta no banco de dados para dados in
```suggestion
Quando precisamos buscar dados para criar a página no lado do servidor, pode-se utilizar `fetch` ou `axios` para buscar por dados externos e uma função com busca direta no banco de dados para dados internos.
```

2024-03-06 14:07 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Quando precisar de dados no lado do cliente, poderá ser utilizados `fetch` e `axios` para buscar dados no servidor via `route handlers`.
```suggestion
Quando precisar de dados no lado do cliente, poderão ser utilizados `fetch` e `axios` para buscar dados no servidor via `route handlers`.
```

2024-03-06 14:08 UTC, EdPPF commented on Execucao/next.js/guia_app.md
> +Os dados coletados podem ser utilizados do jeito que for necessário, exemplo de uso abaixo:
```suggestion
Os dados coletados podem ser utilizados do jeito que for necessário, como no exemplo abaixo:
```
ou algo assim.

2024-03-06 14:14 UTC, EdPPF requested changes
@PedroAmorimG , fiz a review da sua PR até agora. São só umas sugestões de estrutura do que você escreveu e algumas correções de português, mas no conteúdo em si não consegui achar nenhum erro.

E, aliás, se você tiver recebido uns 10 emails sobre meus comentários, foi mal... Ainda tô aprendendo a usar essa feature do GitHub.

2025-03-26 17:06 UTC, closed without merging