Components
StructCE/DocStruct_old pull request #5
Opened 2023-09-07 19:13 UTC by JoaoS4ntos

2023-09-10 20:17 UTC, artistrea requested changes
A ideia dessa documentação é dar um "Quick Start" pra quem quiser só pegar o componente e usar logo ele. Por isso, vale a pena alterar, nesta documentação, os exemplos que ficaram mais complexos.

Recomendo, além de considerar as alterações que sugeri ao longo do código:
- [ ] colocar uma seção de como adicionar cada componente a um projeto novo.
Exemplo com o Modal:
```md
Para adicionar ao projeto esse componente, copie os seguintes arquivos para o seu projeto:
[Modal/index.tsx](https://github.com/StructCE/our-react-components/blob/main/src/components/Modal/index.tsx)
[Modal/styles.module.css](https://github.com/StructCE/our-react-components/blob/main/src/components/Modal/styles.module.css)
```

- [ ] Adicionar um arquivo explicando o que é essa seção de componentes da documentação,
    - [ ] Linkando o projeto no github;
    - [ ] E linkando o projeto no stackblitz: https://stackblitz.com/github/StructCE/our-react-components/tree/main?file=README.md,src%2FApp.tsx

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/Button.md
> +O componente Button é uma forma rápida de criar botões estilizados em suas aplicações React. Ele aceita várias propriedades, permitindo que você personalize facilmente a aparência e o comportamento d
```suggestion
O componente Button é uma forma rápida de criar botões padronizados em suas aplicações React. A ideia é centralizar os estilos padrões de um botão no componente, mantendo as propriedades de um `<button />` comum.
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/Carousel.md
> +1 - Crie um array de imagens para o Carousel, no qual cada imagem contenha o endereço da imagem (url) e um texto alternativo(alt).
```suggestion
1 - Crie um array de imagens para o Carousel, no qual cada imagem contenha um id, o endereço da imagem (url) e um texto alternativo(alt).
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/DropdownMenu.md
> +Lembre-se de instalar a biblioteca '@radix-ui/react-alert-dialog' pelo comando : `npm install @radix-ui/react-alert-dialog`
Estamos começando a usar `pnpm` no lugar de `npm`/`yarn`
```suggestion
Lembre-se de instalar a biblioteca '@radix-ui/react-alert-dialog' pelo comando : `pnpm install @radix-ui/react-alert-dialog`
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/FormFactory.md
> +Antes de usar o componente FormFactory, certifique-se de que a biblioteca Zod esteja instalada em seu projeto. Você pode instalá-la com o comando: `npm install zod`
```suggestion
Antes de usar o componente FormFactory, certifique-se de que a biblioteca Zod esteja instalada em seu projeto. Você pode instalá-la com o comando: `pnpm install zod`
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/FormFactory.md
> +- inputAtrr: Um objeto com os atributos da tag input e seus respectivos valores.
Está faltando a propriedade `transform`.

```suggestion
- fields: Um objeto em que cada chave corresponde a um campo no seu esquema Zod e os valores são objetos com as seguintes propriedades:

    - label: O rótulo do campo.

    - defaultValue: O valor padrão do campo.

    - inputAtrr: Um objeto com os atributos da tag input e seus respectivos valores.
    
    - transform: Uma função que recebe o valor atual do input (sempre uma string) para converter no valor do schema (pode ser número, pode capitalizar a string, etc...)
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/FormFactory.md
> +```
O exemplo no repositório de componentes não é o ideal para um Ctrl+C Ctrl+V rápido. Além disso, A utilização do FormFactory é feita em 3 partes:
- Validação zod;
- Criação do componente usando `FormFactory(formInfo)`;
- Utilização do componente

Duas dessas partes estavam faltando no exemplo, então é melhor ter algo como:
```suggestion
// definindo validação do form:
const loginSchema = z.object({
  email: z.string().email({ message: "Email inválido!" }),
  password: z
    .string()
    .min(6, { message: "Senha deve ter pelo menos 6 caracteres!" }),
});

// criando o componente de formulário:
export const LoginForm = FormFactory({
  schema: loginSchema,
  fields: {
    email: {
      label: "Email *",
      defaultValue: "",
      inputAtrr: { type: "email" },
    },
    password: {
      label: "Senha *",
      defaultValue: "",
      inputAtrr: { type: "password" },
    },
  },
});

// Então pode usar a tag <LoginForm /> em algum componente qualquer:
const LoginPage = () => {
    return <LoginForm
              onValidSubmit={(user) => {
                api
                  .get("/users/login", user)
                  // eslint-disable-next-line no-alert
                  .then(() => alert("logado com sucesso"))
                  // eslint-disable-next-line no-alert
                  .catch((er) => alert(er));
              }}
              onInvalidSubmit={() => {
                // opa
              }}
              buttonContent="Entrar"
    />
}
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/Modal.md
> +`npm install @radix-ui/react-dialog`
```suggestion
`pnpm install @radix-ui/react-dialog`
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/RadioInput.md
> +`npm install @radix-ui/react-radio-group`
```suggestion
`pnpm install @radix-ui/react-radio-group`
```

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/RadioInput.md
Mesma coisa que FormFactory. O exemplo está cheio de coisa que não tem relação com o RadioGroup.

Simplifique o exemplo desta documentação.

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/Table.md
Por mais que goste bastante do caso de uso mostrado nesse exemplo, ainda acho que ele tá grande demais pra dar uma noção de como usar a Table.

2023-09-10 20:17 UTC, artistrea commented on Diretoria Projetos/components/Table.md
> +```
Talvez fique mais óbvio como <Table /> funciona se deixarmos o tipo do User antes?

```suggestion
// Normalmente esse tipo viria do prisma, etc.
export type User = {
  id: number;
  user_name: string;
  age: number;
  status: "active" | "deactivated";
  role: "super_admin" | "admin" | "user";
};

// como não é dinâmico, pode ser colocado fora do componente:
const shownFields: GenericFields<User[]> = [
  // { title: "Id", name: "id" },
  { title: "Usuário", name: "user_name" },
  // { title: "Idade", name: "age" },
  // { title: "Status", name: "status" },
  { title: "Cargo", name: "role" },
];

const actions: GenericRowAction<User[]>[] = [
  {
    title: "Visualizar",
    Icon: ShowIcon,
    onClick: (row) =>
      // eslint-disable-next-line no-alert
      alert(
        `VISUALIZANDO OS DADOS DE ${row.user_name}\n\n ${JSON.stringify(
          row,
          null,
          2
        )}`
      ), // chamar api
  },
  {
    title: "Editar",
    Icon: EditIcon,
    // eslint-disable-next-line no-alert
    onClick: (row) =>
      alert(
        `EDITANDO OS DADOS DE ${row.user_name}\n\n ${JSON.stringify(
          row,
          null,
          2
        )}`
      ), // chamar api
  },
  {
    title: "Deletar",
    Icon: TrashIcon,
    // eslint-disable-next-line no-alert
    onClick: (row) =>
      alert(
        `DELETANDO OS DADOS DE ${row.user_name}\n\n ${JSON.stringify(
          row,
          null,
          2
        )}`
      ), // chamar api
  },
];

export function TableExample() {
  // api call, etc
  const users = getUsers();

  // pode paginar, filtrar, etc
  const shownUsers = users.filter((u) => u.status !== "deactivated");

  return (
    <PageContainer>
      <Table
        title="Usuários"
        fields={shownFields}
        actions={actions}
        rows={shownUsers}
        breakPointWidth={900}
      />
    </PageContainer>
  );
}

function getUsers() {
  const users: User[] = [
    { id: 1, user_name: "art", age: 20, status: "active", role: "admin" },
    {
      id: 2,
      user_name: "Tata Werneck",
      age: 3,
      status: "deactivated",
      role: "user",
    },
    {
      id: 3,
      user_name: "Caetas",
      age: 0,
      status: "active",
      role: "user",
    },
    {
      id: 4,
      user_name: "Nicolau",
      age: 23,
      status: "active",
      role: "super_admin",
    },
    {
      id: 5,
      user_name: "Renatinho sangue bom (demais)",
      age: 250,
      status: "active",
      role: "user",
    },
    {
      id: 6,
      user_name: "Tres21",
      age: 321,
      status: "deactivated",
      role: "admin",
    },
  ];

  return users;
}

```
```

2023-09-18 01:42 UTC, JoaoS4ntos commented on Diretoria Projetos/components/RadioInput.md
Mudei o exemplo, agr está mais prático e reduzido

2023-09-18 01:45 UTC, JoaoS4ntos commented on Diretoria Projetos/components/Table.md
mudei esse exemplo tambem, acho q ficou melhor

2023-09-24 22:06 UTC, artistrea requested changes

2023-09-24 22:06 UTC, artistrea commented on components/Button.md
> +[Button/example.tsx](https://github.com/StructCE/our-react-components/blob/main/src/components/Button/example.tsx)
O exemplo não é necessário levar pro novo projeto
```suggestion
```

2023-09-24 22:06 UTC, artistrea commented on components/RadioInput.md
> +[RadioInput/svgs.tsx](https://github.com/StructCE/our-react-components/blob/main/src/components/RadioInput/example/svgs.tsx)
As svgs não são necessárias para fazer o RadioInput funcionar
```suggestion
```

2023-09-24 22:06 UTC, artistrea commented on components/index.md
> +A documentação explica o que são e como utilizar cada componente supracitado.
Esse trecho vai ficar desatualizado com o tempo, e é redundante

2023-09-25 23:46 UTC, merged