tRPC outline
StructCE/DocStruct_old pull request #6
Opened 2023-09-15 20:05 UTC by MatheusNevs

Documentação para tRPC, explicando o que é, como instalar e como usar.

2023-09-28 13:27 UTC, artistrea requested changes
- [ ] Coloca a documentação de trpc em `execucao` ao invés de `Diretoria Projetos`

2023-09-28 13:27 UTC, artistrea commented on Diretoria Projetos/trpc/pratica.md
> +!!!
Acho que fica melhor se ocultar esse trecho. Primeiro que essa parte de "requisições GET e CREATE" parece confundir a interface com bancos de dados e com uma api.
Aqui é uma simulação de banco de dados, então "requisições GET e CREATE" na verdade é "métodos SELECT e CREATE"
De qualquer maneira, acho bom só não colocar esse trecho de código, pra evitar confusão.
```suggestion
```

2023-09-28 13:27 UTC, artistrea commented on Diretoria Projetos/trpc/pratica.md
> +## Criando a instância de rota tRPC
Eu não entendo o que o título quer dizer. Se pá trocar por algo sem palavras técnicas, ou mais fácil de entender.

2023-09-28 13:27 UTC, artistrea commented on Diretoria Projetos/trpc/pratica.md
> +No back-end, criaremos um arquivo `trpc.ts` onde inicializaremos a instância tRPC e exportaremos o roteador `router` da instância, para definirmos as rotas, e o protocolo de procedimento, definido co
É melhor explicar do que declarar o que está fazendo. Tipo, ao invés de falar que tá instanciando um negócio e exportando, fale o porque fazer isso.

O que seria um publicProcedure? Existe um privateProcedure? Cite essas coisas, mesmo que não mostre
Cite também que a ideia de "procedures" e centralizar essas exportações é facilitar reuso de comportamento entre rotas diferentes, pois tem como você alterar os comportamentos comuns a toda uma aplicação num único arquivo.

2023-10-02 12:39 UTC, artistrea requested changes

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/explicacao.md
> +Em resumo, tRPC ajuda a tornar a comunicação entre cliente e servidor mais clara, segura e eficiente, uma vez que elimina a ambiguidade na troca de dados, tornando o código mais fácil de manter e dep
Faça referência ao typescript no texto. Além disso, deixe claro que tRPC não é uma técnica, e sim uma biblioteca, que se inspira numa técnica de comunicação chamada RPC. Além disso, não realmente usa RPC, que é um protocolo específico de comunicação.

Na base de tudo, tRPC ainda usa HTTP, não RPC. E o sistema de tipos não é forte, é fraquíssimo (estamos falando de javascript + chamada HTTP).

Porém, ele permite uma definição de API usando uma estrutura que permite fácil inferência do que cada Endpoint deve receber e devolver. Colocando a API e o front no mesmo repositório (usando Nextjs, por exemplo), a gente consegue exportar esse tipo para o frontend, e o trpc também nos dá um cliente lá no front que se baseia na tipagem do back pra dar erro de tipos no front, caso estejamos fazendo cagada.

Vê se consegue traduzir mais ou menos o que eu disse

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/instalacao.md
Cita, além da instalação mínima, a instalação recomendada para react, com [react query](https://trpc.io/docs/client/react), e a para [nextjs](https://trpc.io/docs/client/nextjs)

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/pratica.md
> +Assim, criaremos um arquivo `trpc.ts` onde inicializaremos o tRPC por meio de uma `const t` (nome usado somente para exemplo) e exportaremos as propriedades `router`e `procedure` da instância de clas
Que eu saiba, o trpc não funciona através de classes. Pelo contrário, ele funciona através da chamada e definição de funções. Se fosse com classe, teria algo como `new ClasseSlaOQue()`.

A linha 15 está errada pois fala novamente de classes.

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/pratica.md
> +Porém, não faria sentido definirmos as rotas de comunicação entre o cliente e o servidor se não temos por onde fazer essa comunicação. Então também precisamos usar a propriedade `procedure` que está
Não está claro o que quis dizer.
Também não entendi o que quis dizer com o segundo parágrafo.

As rotas da api (`/api/users`) são definidas usando o `router`, e as funções a serem chamadas em cada rota são definidas usando `procedure` (`procedure.getAllUsers() {}`).

A rota direciona para o procedimento, e ambos são utilizados pois permitem coisinhas especiais, que não são abordados nessa documentação, além de permitirem a inferência de tipos.

Não sei se deu pra sacar. A `procedure` não tem nada a ver com `por onde fazer essa comunicação`

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/pratica.md
> +- `subscription` cria uma ligação persistente com o servidor e recebe mudanças.
```suggestion
- `subscription` cria uma ligação persistente com o servidor e recebe mudanças. É o famoso websocket
```

2023-10-02 12:39 UTC, artistrea commented on Execucao/trpc/pratica.md
> +Os campos nos quais deseja fazer alguma validação coloque z.tipoDeDadoDesejado(validação desejada), exemplo:
Não é exatamente assim que se usa zod. A determinação do tipo de dados desejado já serve pra fazer a validação. Faz referência pra documentação deles, se for mais fácil: https://zod.dev/?id=basic-usage

2023-10-04 01:30 UTC, MatheusNevs commented on Execucao/trpc/pratica.md
> +Porém, não faria sentido definirmos as rotas de comunicação entre o cliente e o servidor se não temos por onde fazer essa comunicação. Então também precisamos usar a propriedade `procedure` que está
Acho que saquei a ideia

2023-10-04 01:32 UTC, MatheusNevs commented on Execucao/trpc/pratica.md
> +Os campos nos quais deseja fazer alguma validação coloque z.tipoDeDadoDesejado(validação desejada), exemplo:
Beleza, essa parte de "validação desejada" realmente nao ficou boa. Coloquei a referência pra documentação deles e tirei essa parte que deixou confusa.

2023-10-21 14:28 UTC, merged