[DRAFT] Typescript Doc
StructCE/DocStruct_old pull request #9
Opened 2023-09-24 18:30 UTC by pafev

###Tipagens abordadas:
- props
- useState
- useContext
- eventos (onChange, onSubmit)
- children e componentes (ReactNode, ReactElement, HTMLElement)
- prop style

###Possíveis altearções:
- adicionar tipagem para useReducer
- adicionar como manipular e tipar funções async (dá bug se passar em um onClick)
- explicar DOMElement

2023-09-26 19:58 UTC, artistrea requested changes
Como isso não é diretamente relacionado com o T3 stack, acho bom deixar separado. Tiraria também da Diretoria Projetos.
 - [x] Colocar documentação numa pasta como ´doc. técnica/typescript´ ou `execução/typescript`;
 - [x] Separar typescript puro do React TS;

Além disso, é super arriscado ter numa documentação para quem tá iniciando em typescript esse tanto de exemplo com interface. Interface tem um caso de uso muito específico (biblioteca e possibilitar estender um tipo depois de sua declaração inicial). Sugiro citar os dois, suas difereças, o perigo de interface, se quiser falar da tua preferência, pode, e usar só type nos exemplos.

- [x] A não ser que tenha uma razão além de preferência, coloca type nos exemplos

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +
Colocar um alerta do retype BEM VERMELHO sobre os perigos de usar interface

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +Vale reiterar que o TypeScript não é uma nova linguagem. No final, todo seu código irá ser convertido em JavaScript, para quando for lido pelo compilador.
```suggestion
Vale reiterar que o TypeScript não é uma nova linguagem. No final, todo seu código irá ser transpilado (convertido) em JavaScript, para poder ser interpretado.
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +
Acho bomm ter um: Pra quê usar typescript?

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
Acho melhor separar o typescript pra React em outro arquivo, e ter uma abordagem menos ligada a framework inicialmente.

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +const [state, setState] = useState("string")
```suggestion
const [state, setState] = useState("valor inicial")
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +const useGetTheme = () => useContext(ThemeContext);
```suggestion
const useThemeContext = () => useContext(ThemeContext);
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +    <form/>
```suggestion
    </form>
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +import { useState, type FormEvent } from 'react';
```suggestion
import {
  useState,
  type FormEvent,
  type ChangeEvent,
  type FormEventHandler,
} from "react";
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +
Acho que seria massa mostrar outra alternativa
```suggestion
  const handleSubmitAlternative: FormEventHandler<HTMLFormElement> = (
    event // tipo do argumento já está especificado pelo tipo da função
  ) => {
    event.preventDefault();
  };
```

2023-09-26 19:58 UTC, artistrea commented on Diretoria Projetos/stack_T3/typescript/explicacao.md
> +```
Acho bem mais fácil usar isto, ao invés de ficar lembrando qual é qual. Eu colocaria como primeiro exemplo esse daqui:
```
type MyComponentProps = React.PropsWithChildren<{
    title: string
}>
```

2023-09-26 20:04 UTC, artistrea commented
Sobre as Possíveis alterações:

- adicionar tipagem para useReducer
- adicionar como manipular e tipar funções async (dá bug se passar em um onClick)
- explicar DOMElement

useReducer acho que não (nunca usamos),
Acho que pode valer a pena falar sobre Promise,
e DOMElement nem faço ideia de pra que serve

2023-10-22 00:32 UTC, artistrea requested changes
- [x] Colocar as coisas de typescript em react dentro da pasta de typescript;
- [ ] Aumentar a quantidade de metadados e melhorar os ícones usados;
    - Use como base a [PR](https://github.com/StructCE/DocStruct/pull/15/files#diff-7b2fd61a372cb243593e60d78f8bbb220ad9652df3c4cae161bd812f6d71a9ef), que segue as dicas dadas pelo Araújo
- [x] Só deve existir um H1 por página, em `explicação` tem alguns H1 diferentes.
- [ ] Uma dica pra ficar melhor de acompanhar textos maiores: chamar atenção para as palavras e frases chave usando negrito, alertas, etc:
    - Usa \*\*em volta da palavra\*\* pra ficar assim: **em volta da palavra**
- [x] Colocar o nome da linguagem no bloco de código, para ter *syntax highlight*:
    - É assim que se inicia um bloco de código tsx, por exemplo \`\`\`tsx
- [ ] Tá faltando como adicionar typescript a um projeto, e um pouco sobre o `tsconfig`


Essa documentação ficou muito bem escrita!

2023-10-22 00:32 UTC, artistrea commented on Execucao/typescript/explicacao.md
> +Tá, mas ainda não chegamos no tópico principal desta introduçaço né... por que usar o TypeScript? Para começar, ele funciona como uma ferramenta que adiciona tipagem estática ao JavaScript, que pode
introduçaço

2023-10-22 00:32 UTC, artistrea commented on Execucao/typescript/explicacao.md
> +
Eu explicaria o que quer dizer por seguro, citando a segurança e facilidade de manutenção e modificação do código

2023-10-22 00:32 UTC, artistrea commented on Execucao/typescript/explicacao.md
> +    return false;
Quem nunca fez isso? kkkkkk
```suggestion
    return num >= 0;
```

2023-10-22 00:32 UTC, artistrea commented on Execucao/typescript_react/explicacao.md
> +### Componentes (ReactNode, ReactElement, HTMLElement)
Acho que esse trecho devia ser subtópico de Tipando Props, não?

2023-10-22 00:32 UTC, artistrea commented on Execucao/typescript_react/explicacao.md
> +### Props de estilização
Acho que esse trecho também devia ser subtópico de Tipando Props, não?

2023-10-22 01:06 UTC, pafev commented on Execucao/typescript_react/explicacao.md
> +### Componentes (ReactNode, ReactElement, HTMLElement)
hmmm aí eu teria que fazer uma divisão diferente, porque este subtópico e o de props de estilização utilizam coisas do @types/react, e por isso tão neste tópico em que estão. Aí eu teria que fazer uma divisão do tipo

2023-10-22 01:10 UTC, pafev commented on Execucao/typescript_react/explicacao.md
> +### Componentes (ReactNode, ReactElement, HTMLElement)
Ou seja, seria mover o Tipando Props pra dentro do tópico Pacote @types/react
Você acha que assim ficaria melhor?

2023-10-27 13:34 UTC, pafev commented on Execucao/typescript/explicacao.md
> +
Não entendi, a explicação do "por que seguro" já não está no subtópico "Verificador de Tipos Estáticos"?

2023-10-30 13:28 UTC, merged